#!/usr/bin/env python3
"""Validate the glossary data and regenerate GLOSSARY.md.

Usage:
    python3 scripts/build.py           # validate + write GLOSSARY.md
    python3 scripts/build.py --check   # validate + fail if GLOSSARY.md is stale (used in CI)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATEGORIES = ROOT / "data" / "categories.json"
TERMS = ROOT / "data" / "terms.json"
OUT = ROOT / "GLOSSARY.md"

REQUIRED = {"term", "category", "definition"}
ALLOWED = REQUIRED | {"aka", "notation", "note", "see_also"}


def anchor(text: str) -> str:
    """Match GitHub's heading-anchor algorithm closely enough for our term names."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\- ]", "", a)
    return a.replace(" ", "-")


def validate(categories, terms):
    errors = []
    cat_ids = {c["id"] for c in categories}
    names = [t.get("term") for t in terms]
    seen = set()
    for i, t in enumerate(terms):
        label = t.get("term", f"entry #{i}")
        missing = REQUIRED - t.keys()
        if missing:
            errors.append(f"{label}: missing {sorted(missing)}")
        extra = t.keys() - ALLOWED
        if extra:
            errors.append(f"{label}: unknown fields {sorted(extra)}")
        if t.get("category") not in cat_ids:
            errors.append(f"{label}: unknown category '{t.get('category')}'")
        if label in seen:
            errors.append(f"{label}: duplicate term")
        seen.add(label)
        for ref in t.get("see_also", []):
            if ref not in names:
                errors.append(f"{label}: see_also '{ref}' does not match any term")
            if ref == label:
                errors.append(f"{label}: see_also points to itself")
    return errors


def render(categories, terms) -> str:
    lines = [
        "# AI & RL Lexicon",
        "",
        "<!-- Generated by scripts/build.py from data/*.json. Do not edit by hand. -->",
        "",
        f"{len(terms)} terms across {len(categories)} topics. "
        "For the searchable version, open `index.html` or the GitHub Pages site.",
        "",
        "## Contents",
        "",
    ]
    for c in categories:
        n = sum(1 for t in terms if t["category"] == c["id"])
        lines.append(f"- [{c['name']}](#{anchor(c['name'])}) ({n})")
    lines.append("")

    for c in categories:
        lines += [f"## {c['name']}", "", f"_{c['description']}_", ""]
        for t in (t for t in terms if t["category"] == c["id"]):
            lines.append(f"### {t['term']}")
            lines.append("")
            meta = []
            if t.get("aka"):
                meta.append(f"Also: {t['aka']}")
            if t.get("notation"):
                meta.append(f"Notation: `{t['notation']}`")
            if meta:
                lines += [" · ".join(meta), ""]
            lines += [t["definition"], ""]
            if t.get("note"):
                lines += [f"> **In the room:** {t['note']}", ""]
            if t.get("see_also"):
                links = ", ".join(f"[{r}](#{anchor(r)})" for r in t["see_also"])
                lines += [f"See also: {links}", ""]
    return "\n".join(lines).rstrip() + "\n"


def main():
    categories = json.loads(CATEGORIES.read_text(encoding="utf-8"))
    terms = json.loads(TERMS.read_text(encoding="utf-8"))
    errors = validate(categories, terms)
    if errors:
        print("Validation failed:\n  " + "\n  ".join(errors))
        sys.exit(1)
    md = render(categories, terms)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != md:
            print("GLOSSARY.md is out of date. Run: python3 scripts/build.py")
            sys.exit(1)
        print(f"OK: {len(terms)} terms valid, GLOSSARY.md up to date.")
        return
    OUT.write_text(md, encoding="utf-8")
    print(f"Wrote GLOSSARY.md ({len(terms)} terms).")


if __name__ == "__main__":
    main()
